# Generated by Django 5.2.8 on 2026-03-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_alter_job_employer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('exam_duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('upload_type', models.CharField(choices=[('pdf', 'PDF'), ('json', 'JSON')], max_length=10)),
                ('exam_file', models.FileField(blank=True, null=True, upload_to='aptitude_tests/pdfs/')),
                ('exam_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aptitude_test', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
