# Generated by Django 5.2.8 on 2026-03-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_aptitudetest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aptitudetest',
            name='exam_json',
        ),
        migrations.AddField(
            model_name='aptitudetest',
            name='question_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of MCQ questions', null=True),
        ),
    ]
