# Generated by Django 5.2.8 on 2026-03-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_aptitudetest_exam_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aptitudetest',
            name='question',
            field=models.TextField(blank=True, help_text='JSON string containing questions and options', null=True),
        ),
    ]
